
###
curl -X POST -k -vu test_client:test_secret http://localhost:8095/oauth/token -H "Accept: application/json" -d "password=password&username=admin&grant_type=password&scope=read&client_secret=test_secret&client_id=test_client"

###
curl "https://devops.datenkollektiv.de/renderBannerTxt?text=TwigCodes&font=slant"

###
GET http://localhost:8095/oauth/authorize?response_type=token&client_id=discoveryClient&redirect_uri=http://localhost/123

###
GET http://localhost:8095/oauth/check_token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbInJlYWQiXSwiZXhwIjoxNTM0NjI1MjQwLCJhdXRob3JpdGllcyI6WyLotoXnuqfnrqHnkIblkZgiXSwianRpIjoiNjJlYmJhZmUtY2VkZi00YTkwLTk4MzEtMWNmOWMwZDliMTVkIiwidGVuYW50IjoiYWRtaW4iLCJjbGllbnRfaWQiOiJ0ZXN0X2NsaWVudCJ9.cE-fc3mB1HY-DPqhyI6pX5VRbbIlqip0q49viawnDIM

###
GET http://localhost:8095/actuator/


###
GET http://localhost:8095/oauth/check_token?token=123

###
GET http://localhost:8095/oauth/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbInJlYWQiXSwiZXhwIjoxNTM0NjI1MjQwLCJhdXRob3JpdGllcyI6WyLotoXnuqfnrqHnkIblkZgiXSwianRpIjoiNjJlYmJhZmUtY2VkZi00YTkwLTk4MzEtMWNmOWMwZDliMTVkIiwidGVuYW50IjoiYWRtaW4iLCJjbGllbnRfaWQiOiJ0ZXN0X2NsaWVudCJ9.cE-fc3mB1HY-DPqhyI6pX5VRbbIlqip0q49viawnDIM

###
GET http://localhost:8099/api/management/push?content=ter
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbInJlYWQiXSwiZXhwIjoxNTM0NjI1MjQwLCJhdXRob3JpdGllcyI6WyLotoXnuqfnrqHnkIblkZgiXSwianRpIjoiNjJlYmJhZmUtY2VkZi00YTkwLTk4MzEtMWNmOWMwZDliMTVkIiwidGVuYW50IjoiYWRtaW4iLCJjbGllbnRfaWQiOiJ0ZXN0X2NsaWVudCJ9.cE-fc3mB1HY-DPqhyI6pX5VRbbIlqip0q49viawnDIM

###
http://localhost:8095/oauth/authorize?response_type=code&client_id=discoveryClient&redirect_uri=http://localhost:8099
###
curl -i -d "grant_type=authorization_code&code=LBeTKY&client_id=discoveryClient&client_secret=discoverySecret" -X POST http://localhost:8095/oauth/token

###
POST https://api.weixin.qq.com/sns/oauth2/access_token?appid=wxd5eaca40a1d44102&secret=8789092f7ce0facb4687e1c07d9d8e34&code=CODE&grant_type=authorization_code

###
curl -X POST -k -vu login-app:855ee82d-38d0-4d6a-b7e0-22726097cc96 http://localhost:9999/auth/realms/twigcodes/protocol/openid-connect/auth -H "Accept: application/json" -d "response_type=token&password=password&username=twiguser&grant_type=password&scope=profile&client_secret=855ee82d-38d0-4d6a-b7e0-22726097cc96&client_id=login-app"

###
POST http://localhost:9999/auth/realms/twigcodes/protocol/openid-connect/auth
Content-Type: application/x-www-form-urlencoded

password=password&username=twiguser&grant_type=password&scope=openid&client_secret=855ee82d-38d0-4d6a-b7e0-22726097cc96&client_id=login-app

###
POST https://auth.twigcodes.com/auth/realms/twigcodes/protocol/openid-connect/auth HTTP/1.1
Content-Type: application/x-www-form-urlencoded

response_type=token
&client_id=login-app
&client_secret=b888bb5b-2627-453e-b3a7-2fb79c923032
&redirect_uri=http://localhost:8080/webjars/springfox-swagger-ui/oauth2-redirect.html
&state=V2VkIFNlcCAyNiAyMDE4IDIyOjAwOjAzIEdNVCswODAwICjkuK3lm73moIflh4bml7bpl7Qp

###
POST https://auth.twigcodes.com/auth/realms/twigcodes/protocol/openid-connect/token
Authorization: Basic login-app 942bfe03-9851-4db8-b100-8393c9c6c9cd
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Accept: application/json

password=X*bcYp4x&grant_type=password&username=twigadmin

###
POST http://pcustomer1.bjcapitalland.com.cn/customer-service-houseinfosvc/api/service/jdQueryHouseInfo

{
    "pageNumber": 1,                 //分页：当前第几页
    "pageSize": 1,                    //分页：每页显示条数
    "projectId": "PROJECT1436",    //项目ID
    "periodId": "PERIOD1671"      //分期ID
}
