# 定义服务端口
server:
  port: ${SERVER_PORT:8095}
spring:
  profiles:
    active: dev
  jooq:
    sql-dialect: mysql
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    # 让所有监控接口都接受 web 访问
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/
uaa.jwtSigningKey: mySecret

---
spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_UPPER=false
    username: sa
    password:
  flyway:
    locations: classpath:db/migration/h2
  h2:
    console:
      enabled: true
  # cloud:
  #   service-registry:
  #     auto-registration:
  #       enabled: false
  #   config:
  #     enabled: false
logging:
  level:
    root: ERROR
    org.springframework: DEBUG
    org.hibernate: DEBUG
    com.netflix.eureka: 'OFF'
    com.twigcodes.uaa: DEBUG
---

spring:
  profiles: prod
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ENDPOINT:localhost:3306}/${MYSQL_DATABASE:twig_auth}?useSSL=false
    username: ${MYSQL_USERNAME:test}
    password: ${MYSQL_PASSWORD:pass}
  flyway:
    locations: "classpath:db/migration/mysql"
    user: ${MYSQL_USERNAME:test}
    password: ${MYSQL_PASSWORD:pass}
logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    com.netflix.eureka: ERROR
    com.twigcodes.uaa: ERROR
